FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json turbo.json tsconfig.base.json ./
COPY apps/api ./apps/api
COPY packages ./packages
RUN npm install
RUN npm run build --filter=@enterprise/api

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4000
CMD ["node", "dist/main.js"]
